module PurchaseOrderParser
  class Parser
    def initialize file_path
      @file   = File.open file_path, 'rb'
      @reader = PDF::Reader.new @file
      @lines  = {}
    end

    # TODO move this method/ivar to ctor?
    def text
      @text ||= @reader.pages.map! do |page|
        page.text
      end.map! do |line|
        line.split /\n+/
      end.flatten
        #line.split /\n+/
#        line.split /\n+/ if line.include? '\n'
#        line.split /\\n+/ if line.include? '\\n'
      #end.map do |l|
      #  l.split /\\n+/
      #end
        #line == ''
      #end.map do |line|
    end

    # Each line should be an array of strigs, where the multiple spaces have been split on.
    def lines
      @lines ||= text.map do |line|
        line.split /\s{2}/
      end
      puts "LINES? #{@lines}"
      @lines
    end

    # Basically a shortcut to the hash ?? generated by text.
    def number
      #puts "#{@reader.pages.map!{|x| x.text.class}  }"
      text[:order_number]
    end
  end
end
